import React from "react";

export default (props) => {
  return (
    <div>
      <button>1</button>
      <button>2</button>
      <button>3</button>
      <button>4</button>
      <button>5</button>
      <button>6</button>
      <button>7</button>
      <button>8</button>
      <button>9</button>
      <button>10</button>
      <button>11</button>
      <button>12</button>
      <button>13</button>
      <button>14</button>
      <button>15</button>
      <button>16</button>
      <button>17</button>
      <button>18</button>
      <button>19</button>
      <button>20</button>
      <button>21</button>
      <button>22</button>
      <button>23</button>
      <button>24</button>
      <button>25</button>
      <button>26</button>
      <button>27</button>
      <button>28</button>
      <button>29</button>
      <button>30</button>
      <button>31</button>
      <button>32</button>
      <button>33</button>
      <button>34</button>
      <button>35</button>
      <button>36</button>
      <button>37</button>
      <button>38</button>
      <button>39</button>
      <button>40</button>
      <button>41</button>
      <button>42</button>
      <button>43</button>
      <button>44</button>
      <button>45</button>
      <button>46</button>
      <button>47</button>
      <button>48</button>
      <button>49</button>
      <button>50</button>
      <button>51</button>
      <button>52</button>
      <button>53</button>
      <button>54</button>
      <button>55</button>
      <button>56</button>
      <button>57</button>
      <button>58</button>
      <button>59</button>
      <button>60</button>
    </div>
  );
};
